const data=[
    {
        id:1,
        itemName: "NIKE AIR MAX 1",
        subName: "PURE PLATINUM RACER BLUE",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:48000,
        priceUSD:240,
        stock: 5,
        DetailImage: ["../DetailImg/1-NIKE AIR MAX 1 PURE PLATINUM RACER BLUE.jpg"],
        imageProduct: ["../ItemsImg/1-NIKE AIR MAX 1 PURE PLATINUM RACER BLUE.jpg"] 
    },
    {
        id:2,
        itemName: "NIKE AIR JORDAN",
        subName: "JUMPMAN CARGO WOVEN SHORTS BLACK",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Indumentaria",
        price:20300,
        priceUSD:100,
        stock: 5,
        DetailImage: ["../DetailImg/JORDAN JUMPMAN CARGO WOVEN SHORTS BLACK.jpg"],
        imageProduct: ["../ItemsImg/JORDAN JUMPMAN CARGO WOVEN SHORTS BLACK.jpg"] 
    },
    {
        id:3,
        itemName: "NIKE AIR JORDAN",
        subName: "JUMPMAN STATEMENT HOODED JACKET",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Indumentaria",
        price:36000,
        priceUSD:180,
        stock: 5,
        DetailImage: ["../DetailImg/AIR JORDAN JUMPMAN STATEMENT HOODED JACKET.jpg"],
        imageProduct: ["../ItemsImg/AIR JORDAN JUMPMAN STATEMENT HOODED JACKET.jpg"] 
    },
    {
        id:4,
        itemName: "NIKE AIR MAX 1",
        subName: "DYNAMIC BERRY",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category: "Calzado",
        price: 36000,
        priceUSD: 180,
        stock: 5,
        DetailImage: ["../DetailImg/2-NIKE AIR MAX 1 DYNAMIC BERRY.jpg"], 
        imageProduct: ["../ItemsImg/2-NIKE AIR MAX 1 DYNAMIC BERRY.jpg"]
    },
    {
        id:5,
        itemName: "NIKE DUNK HIGH",
        subName: "1985 RED ACID WASH",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price: 42000,
        priceUSD: 210,
        stock: 5,
        DetailImage: ["../DetailImg/3-NIKE DUNK HIGH 1985 RED ACID WASH.jpg"], 
        imageProduct: ["../ItemsImg/3-NIKE DUNK HIGH 1985 RED ACID WASH.jpg"] 
    },
    {
        id:6,
        itemName: "NIKE DUNK HIGH",
        subName: "SB TRUCK IT BLACK",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category: "Calzado",
        price: 34000,
        priceUSD: 170,
        stock: 5,
        DetailImage: ["../DetailImg/4-NIKE DUNK HIGH SB TRUCK IT BLACK.jpg"],  
        imageProduct: ["../ItemsImg/4-NIKE DUNK HIGH SB TRUCK IT BLACK.jpg"]
    },
    {
        id:7,
        itemName: "ANTI SOCIAL SOCIAL CLUB MIND GAMES",
        subName: "HOODIE BLACK",
        brand: "ANTI SOCIAL SOCIAL CLUB",
        brandImg:["../Img/ASSCLogo.jpg"],
        category:"Indumentaria",
        price:47300,
        priceUSD:235,
        stock: 5,
        DetailImage: ["../DetailImg/Anti Social Social Club Mind Games Hoodie (SS20) Black.jpg"],
        imageProduct: ["../ItemsImg/Anti Social Social Club Mind Games Hoodie (SS20) Black.jpg"]
    },
    {
        id:8,
        itemName: "NIKE DUNK LOW",
        subName: "EMB NBA 75TH ANNIVERSARY CHICAGO",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price: 43000,
        priceUSD: 215,
        stock: 5, 
        DetailImage: ["../DetailImg/5-NIKE DUNK LOW EMB NBA 75TH ANNIVERSARY CHICAGO.jpg"], 
        imageProduct: ["../ItemsImg/5-NIKE DUNK LOW EMB NBA 75TH ANNIVERSARY CHICAGO.jpg"]
    },
    {
        id:9,
        itemName: "NIKE HERITAGE",
        subName: "CROSSBODY BAG",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Accesorios",
        price:18000,
        priceUSD:90,
        stock: 5,
        DetailImage: ["../DetailImg/Nike Heritage Crossbody Bag.jpg"],
        imageProduct: ["../ItemsImg/Nike Heritage Crossbody Bag.jpg"] 
    },
    {
        id:10,
        itemName: "NIKE DUNK LOW",
        subName: "REVERSE PAPA BEAR",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price: 53000,
        priceUSD: 265,
        stock: 5, 
        DetailImage: ["../DetailImg/6-NIKE DUNK LOW REVERSE PAPA BEAR.jpg"], 
        imageProduct: ["../ItemsImg/6-NIKE DUNK LOW REVERSE PAPA BEAR.jpg"]
    },
    {
        id:11,
        itemName: "NIKE DUNK LOW SB",
        subName: "CHUNKY DUNKY",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price: 310000,
        priceUSD: 1550,
        stock: 5, 
        DetailImage: ["../DetailImg/7-NIKE DUNK LOW SB CHUNKY DUNKY.jpg"], 
        imageProduct: ["../ItemsImg/7-NIKE DUNK LOW SB CHUNKY DUNKY.jpg"]
    },
    {
        id:12,
        itemName: "ANTI SOCIAL SOCIAL CLUB PULSE CHECK",
        subName: "T-SHIRT BLACK",
        brand: "ANTI SOCIAL SOCIAL CLUB",
        brandImg:["../Img/ASSCLogo.jpg"],
        category:"Indumentaria",
        price:25900,
        priceUSD:130,
        stock: 5,
        DetailImage: ["../DetailImg/Anti Social Social Club Pulse Check T-shirt Black.jpg"],
        imageProduct: ["../ItemsImg/Anti Social Social Club Pulse Check T-shirt Black.jpg"] 
    },
    {
        id:13,
        itemName: "NIKE DUNK LOW SB",
        subName: "SEAN CLIVER",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price: 154000,
        priceUSD: 770,
        stock: 5, 
        DetailImage: ["../DetailImg/8-NIKE DUNK LOW SB SEAN CLIVER.jpg"], 
        imageProduct: ["../ItemsImg/8-NIKE DUNK LOW SB SEAN CLIVER.jpg"]
    },
    {
        id:14,
        itemName: "NIKE DUNK LOW",
        subName: "SIEMPRE FAMILIA",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:60000,
        priceUSD:300,
        stock:5, 
        DetailImage: ["../DetailImg/9-NIKE DUNK LOW SIEMPRE FAMILIA.jpg"], 
        imageProduct: ["../ItemsImg/9-NIKE DUNK LOW SIEMPRE FAMILIA.jpg"]
    },
    {
        id:15,
        itemName: "BAPE STA PATTERN SHARK",
        subName: "TEE WHITE",
        brand: "BAPE",
        brandImg:["../Img/BapeLogo.jpg"],
        category:"Indumentaria",
        price:39000,
        priceUSD:195,
        stock: 5,
        DetailImage: ["../DetailImg/BAPE Sta Pattern Shark Tee White.jpg"],
        imageProduct: ["../ItemsImg/BAPE Sta Pattern Shark Tee White.jpg"] 
    },
    {
        id:16,
        itemName: "JORDAN CROSSBODY BELT BAG",
        subName: " FANNY PACK HIP WAIST WHITE",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Accesorios",
        price:20000,
        priceUSD:100,
        stock: 5,
        DetailImage: ["../DetailImg/Jordan Crossbody Belt Bag Fanny Pack Hip Waist White.jpg"],
        imageProduct: ["../ItemsImg/Jordan Crossbody Belt Bag Fanny Pack Hip Waist White.jpg"] 
    },
    {
        id:17,
        itemName: "OVO® BACKPACK",
        subName: "TUSCAN BROWN",
        brand: "OVO",
        brandImg:["../Img/OVOLogo.png"],
        category:"Accesorios",
        price:99000,
        priceUSD:495,
        stock: 5,
        DetailImage: ["../DetailImg/OVO® BACKPACK TUSCAN BROWN.jpg"],
        imageProduct: ["../ItemsImg/OVO® BACKPACK TUSCAN BROWN.jpg"] 
    },
    {
        id:18,
        itemName: "NIKE KYRIE",
        subName: "FLYTRAP UNIVERSITY RED",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:45000,
        priceUSD:225,
        stock: 5, 
        DetailImage: ["../DetailImg/10-NIKE KYRIE FLYTRAP UNIVERSITY RED.jpg"], 
        imageProduct: ["../ItemsImg/10-NIKE KYRIE FLYTRAP UNIVERSITY RED.jpg"]
    },
    {
        id:19,
        itemName: "NIKE SB DUNK LOW ",
        subName: "PRO ACG TERRA RED PLUM",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:35000,
        priceUSD:175,
        stock: 5,
        DetailImage: ["../DetailImg/11-NIKE SB DUNK LOW PRO ACG TERRA RED PLUM.jpg"], 
        imageProduct: ["../ItemsImg/11-NIKE SB DUNK LOW PRO ACG TERRA RED PLUM.jpg"]
    },
    {
        id:20,
        itemName: "NIKE SB DUNK LOW ",
        subName: "GRATEFUL DEAD BEARS OPTI YELLOW",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:166000,
        priceUSD:830,
        stock: 5,
        DetailImage: ["../DetailImg/12-NIKE SB DUNK LOW GRATEFUL DEAD BEARS OPTI YELLOW.jpg"], 
        imageProduct: ["../ItemsImg/12-NIKE SB DUNK LOW GRATEFUL DEAD BEARS OPTI YELLOW.jpg"]
    },
    {
        id:21,
        itemName: "NIKE SB DUNK LOW",
        subName: "ATMOSPHERE",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:60000,
        priceUSD:300,
        stock: 5,
        DetailImage: ["../DetailImg/13-NIKE SB DUNK LOW ATMOSPHERE.jpg"],  
        imageProduct: ["../ItemsImg/13-NIKE SB DUNK LOW ATMOSPHERE.jpg"]
    },
    {
        id:22,
        itemName: "CACTUS PLANT FLEA MARKET BORN AGAIN",
        subName: "HOODED SWEATSHIRT GREEN",
        brand: "CACTUS PLANT FLEA MARKET",
        brandImg:["../Img/CPFMLogo.png"],
        category:"Indumentaria",
        price:99000,
        priceUSD:495,
        stock: 5,
        DetailImage: ["../DetailImg/Cactus Plant Flea Market Born Again Hooded Sweatshirt Green.jpg"],
        imageProduct: ["../ItemsImg/Cactus Plant Flea Market Born Again Hooded Sweatshirt Green.jpg"] 
    },
    {
        id:23,
        itemName: "AIR JORDAN 1 HIGH",
        subName: "LIGHT SMOKE GREY",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:60000,
        priceUSD:300,
        stock: 5,
        DetailImage: ["../DetailImg/14-AIR JORDAN 1 HIGH LIGHT SMOKE GREY.jpg"], 
        imageProduct: ["../ItemsImg/14-AIR JORDAN 1 HIGH LIGHT SMOKE GREY.jpg"]
    },
    {
        id:24,
        itemName: "AIR JORDAN 1 MID",
        subName: "TRIPLE WHITE PATENT SWOOSH",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Calzado",
        price:35000,
        priceUSD:175,
        stock: 5,
        DetailImage: ["../DetailImg/15-AIR JORDAN 1 MID TRIPLE WHITE PATENT SWOOSH.jpg"], 
        imageProduct: ["../ItemsImg/15-AIR JORDAN 1 MID TRIPLE WHITE PATENT SWOOSH.jpg"]
    },
    {
        id:25,
        itemName: "ADIDAS X ERIC EMANUEL MCDONALD´S",
        subName: "WINDBREAKER YELLOW",
        brand: "ADIDAS",
        brandImg:["../Img/AdidasLogo.jpg"],
        category:"Indumentaria",
        price:34000,
        priceUSD:170,
        stock: 5,
        DetailImage: ["../DetailImg/Adidas x Eric Emanuel McDonalds Windbreaker Yellow.jpg"], 
        imageProduct: ["../ItemsImg/Adidas x Eric Emanuel McDonalds Windbreaker Yellow.jpg"]
    },
    {
        id:26,
        itemName: "ERIC EMANUEL EE BASIC SHORT",
        subName: "(SS22) RED",
        brand: "ERIC EMANUEL",
        brandImg:["../Img/EELogo.jpg"],
        category:"Indumentaria",
        price:34000,
        priceUSD:170,
        stock: 5,
        DetailImage: ["../DetailImg/Eric Emanuel EE Basic Short (SS22) Red.jpg"], 
        imageProduct: ["../ItemsImg/Eric Emanuel EE Basic Short (SS22) Red.jpg"]
    },
    {
        id:27,
        itemName: "ERIC EMANUEL EE BASIC SHORT",
        subName: "(SS22) ROYAL",
        brand: "ERIC EMANUEL",
        brandImg:["../Img/EELogo.jpg"],
        category:"Indumentaria",
        price:34000,
        priceUSD:170,
        stock: 5,
        DetailImage: ["../DetailImg/Eric Emanuel EE Basic Short (SS22) Royal.jpg"], 
        imageProduct: ["../ItemsImg/Eric Emanuel EE Basic Short (SS22) Royal.jpg"]
    },
    {
        id:28,
        itemName: "ERIC EMANUEL X WARREN LOTAS",
        subName: "JUMP SHOT TEE BLACK",
        brand: "ERIC EMANUEL",
        brandImg:["../Img/EELogo.jpg"],
        category:"Indumentaria",
        price:45000,
        priceUSD:225,
        stock: 5,
        DetailImage: ["../DetailImg/Eric Emanuel x Warren Lotas Jump Shot Tee Black.jpg"], 
        imageProduct: ["../ItemsImg/Eric Emanuel x Warren Lotas Jump Shot Tee Black.jpg"]
    },
    {
        id:29,
        itemName: "FEAR OF GOD ESSENTIALS",
        subName: "PULLOVER HOODIE LIGHT",
        brand: "ESSENTIALS",
        brandImg:["../Img/ESSLogo.jpg"],
        category:"Indumentaria",
        price:42000,
        priceUSD:210,
        stock: 5,
        DetailImage: ["../DetailImg/Fear of God Essentials Pull-Over Hoodie.jpg"], 
        imageProduct: ["../ItemsImg/Fear of God Essentials Pull-Over Hoodie.jpg"]
    },
    {
        id:30,
        itemName: "JORDAN FLIGHT HERITAGE",
        subName: "MEN’S SHORT-SLEEVE T-SHIRT",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Indumentaria",
        price:22500,
        priceUSD:112,
        stock: 5,
        DetailImage: ["../DetailImg/Jordan Flight Heritage Men’s Short-Sleeve T-Shirt.jpg"], 
        imageProduct: ["../ItemsImg/Jordan Flight Heritage Men’s Short-Sleeve T-Shirt.jpg"]
    },
    {
        id:31,
        itemName: "Jordan Jumpman ",
        subName: "Men’s Fleece Pullover Hoodie Light Bordeaux",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Indumentaria",
        price:25000,
        priceUSD:125,
        stock: 5,
        DetailImage: ["../DetailImg/Jordan Jumpman Men’s Fleece Pullover Hoodie Light Bordeaux.jpg"], 
        imageProduct: ["../ItemsImg/Jordan Jumpman Men’s Fleece Pullover Hoodie Light Bordeaux.jpg"]
    },
    {
        id:32,
        itemName: "PALACE CORDURA BODY SHOT",
        subName: "BAG DESERT DPM",
        brand: "PALACE",
        brandImg:["../Img/PALogo.jpg"],
        category:"Accesorios",
        price:31000,
        priceUSD:155,
        stock: 5,
        DetailImage: ["../DetailImg/PALACE CORDURA BODY SHOT BAG DESERT DPM.jpg"], 
        imageProduct: ["../ItemsImg/PALACE CORDURA BODY SHOT BAG DESERT DPM.jpg"]
    },
    {
        id:33,
        itemName: "RIP N DIP VENTILATOR MASK",
        subName: "PURPLE CAMO",
        brand: "RIP N DIP",
        brandImg:["../Img/RNDLogo.jpg"],
        category:"Accesorios",
        price:6500,
        priceUSD:  32,
        stock: 5,
        DetailImage: ["../DetailImg/RIP N DIP VENTILATOR MASK PURPLE CAMO.jpg"], 
        imageProduct: ["../ItemsImg/RIP N DIP VENTILATOR MASK PURPLE CAMO.jpg"]
    },
    {
        id:34,
        itemName: "NIKE DRI-FIT DNA",
        subName: "BANDANA PRINTED SHORTS FIREBERRY",
        brand: "NIKE",
        brandImg:["../Img/NikeLogo.png"],
        category:"Indumentaria",
        price:28000,
        priceUSD:140,
        stock: 5,
        DetailImage: ["../DetailImg/Nike Dri-FIT DNA Bandana Printed Shorts Fireberry.jpg"], 
        imageProduct: ["../ItemsImg/Nike Dri-FIT DNA Bandana Printed Shorts Fireberry.jpg"]
    },
    {
        id:35,
        itemName: "SUPREME CANVAS",
        subName: "BACKPACK (FW20/FW21) BLACK",
        brand: "SUPREME",
        brandImg:["../Img/SuprLogo.jpg"],
        category:"Accesorios",
        price:49000,
        priceUSD:245,
        stock: 5,
        DetailImage: ["../DetailImg/Supreme Canvas Backpack Black.jpg"], 
        imageProduct: ["../ItemsImg/Supreme Canvas Backpack Black.jpg"]
    },
]


export const getData = () => {
    return new Promise((resolve, reject)=> {
        setTimeout(()=>{
            return resolve(data);
        },2000)
    })
}